# Generated by Django 2.1.1 on 2018-09-23 08:51

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Контент сообщения')),
                ('files', models.FileField(blank=True, null=True, upload_to='static/files/upload_to/', verbose_name='Аттач файл')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'запись объявления',
                'verbose_name_plural': 'записи объявления',
                'db_table': 'Объявления',
                'ordering': ['-date_create'],
            },
        ),
    ]
