# Generated by Django 2.1.1 on 2018-10-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('cotegory', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('mobail_pthone', models.IntegerField(unique=True, verbose_name='Сотовый')),
                ('email', models.EmailField(blank=True, max_length=70, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Комментрий')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/img/upload_to/', verbose_name='Фото')),
            ],
        ),
    ]
