# Generated by Django 2.1.1 on 2018-10-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='mobail_pthone',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Сотовый'),
        ),
    ]
