# Generated by Django 2.1.1 on 2018-10-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_auto_20181002_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='mobail_pthone',
            field=models.IntegerField(unique=True, verbose_name='Сотовый'),
        ),
    ]
