# Generated by Django 2.1.1 on 2018-09-26 08:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sert_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('s_text', ckeditor.fields.RichTextField(verbose_name='Контент сообщения')),
                ('s_date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('s_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'запись объявления',
                'verbose_name_plural': 'записи объявления',
                'db_table': 'Сертификация',
                'ordering': ['-s_date_create'],
            },
        ),
    ]
