# Generated by Django 2.1.1 on 2018-09-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_guest',
            options={'ordering': ['-g_date_create']},
        ),
        migrations.AlterModelTable(
            name='post_guest',
            table=None,
        ),
    ]
