# Generated by Django 2.1.1 on 2018-09-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0002_auto_20180928_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_guest',
            name='g_author',
        ),
        migrations.AlterField(
            model_name='post_guest',
            name='g_title',
            field=models.CharField(max_length=250, verbose_name='Кто Вы'),
        ),
    ]
